### ISSUE TITLE
SVG Icons look in Studio broken, fine on device

### ISSUE THREAD

**Issue by ServusJon** [bpxl-labs/StatusBarLayer#12]
<img width="432" alt="bildschirmfoto 2017-10-23 um 11 16 51" src="https://user-images.githubusercontent.com/783416/31881453-d71ebb88-b7e3-11e7-80b4-0b12e01c7cc9.png">

**Comment by NocheVolta** [comment]
I just did a PR to fix it https://github.com/bpxl-labs/StatusBarLayer/pull/13
