### ISSUE TITLE
StatusBar responsive problem

### ISSUE THREAD

**Issue by afnizarnur** [bpxl-labs/StatusBarLayer#7]
Hi, is there any solution for this problem? 
<img width="445" alt="screen shot 2017-08-01 at 2 23 18 pm" src="https://user-images.githubusercontent.com/4648648/28813790-fda1df7a-76c4-11e7-96cb-42ed61f2b185.png">

**Comment by kolebayev** [comment]
@afnizarnur i had a problem with text top margins.
![2017-08-19 17 29 46](https://user-images.githubusercontent.com/24884175/29487800-ff952f84-8507-11e7-97a2-3a9759920600.png)

 i've  played with numbers in coffee file here:
`
getTopMargin = () =>
			if isiPhonePlus()
				return 2
			else if Utils.isMobile()
				return 2
			else
				return 2
`
it worked pretty nice
![2017-08-19 17 59 07](https://user-images.githubusercontent.com/24884175/29487814-21044cb8-8508-11e7-8af9-446771f2ae65.png)

you can change `getBatteryMargin` (line 103) and check what's gonna happen

**Comment by afnizarnur** [comment]
@kolebayev Ah I see, thanks man! I will try it out 👍

**Comment by iconmaster** [comment]
Version 2.1.0 specifically fixes the margin issue as well as others. Please give it a shot.
